

development:
  adapter: postgresql
  encoding: unicode
  database: bebox_developpement
  host: localhost
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: bebox_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: beats_database
  host: localhost
  username: rails
  password: XUQEsieZOD
  pool: 5
