//= require Chart.bundle
//= require chartkick
//= require jquery
//= require jquery-ui
//= require jquery_ujs
//= require bootstrap/affix
//= require bootstrap/alert
//= require bootstrap/button
//= require bootstrap/carousel
//= require bootstrap/collapse
//= require bootstrap/dropdown
//= require bootstrap/tab
//= require bootstrap/transition
//= require bootstrap/scrollspy
//= require bootstrap/modal
//= require bootstrap/tooltip
//= require bootstrap/popover
//= require shared/lib/select2
//= require shared/lib/select2.de
//= require shared/script
//= require_tree ./backend/sidebar
//= require_tree ./backend
//= require_self
console.log("jhdkjdf");